version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
  deploy_development:
    docker:
      - image: circleci/php:7.2-browsers
    steps:
      - add_ssh_keys:
          fingerprints:
            - "59:43:6e:72:dc:75:53:ab:f3:e7:33:2a:05:98:46:a0"
      - checkout
      - run:
          name: Install Deployer
          command: |
            curl -LO https://deployer.org/deployer.phar
            sudo mv deployer.phar /usr/local/bin/dep
            sudo chmod +x /usr/local/bin/dep
      - run:
          name: Deploy
          command: |
            if [ -z `ssh-keygen -F '52.15.170.75'` ]; then
              ssh-keyscan -H '52.15.170.75' >> ~/.ssh/known_hosts
            fi
            dep deploy 52.15.170.75
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy_development:
          requires:
            - build
          filters:
            branches:
              only: master
